name: generate-animation

on:
  # Otomatik olarak her 12 saatte bir çalıştır
  schedule:
    - cron: "0 */12 * * *" 
  
  # Herhangi bir zamanda işlemi manuel olarak çalıştırmayı sağlar
  workflow_dispatch:
  
  # Ana dalda her push'ta çalıştır
  push:
    branches:
    - main
    
jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # Bir GitHub kullanıcısının katkılar grafiğinden yılan oyunu oluşturur, çıktı olarak bir SVG animasyonu sağlar
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: semamehmetcik
          # dist klasörüne çıktıları sağlar
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
      # <build_dir> içeriğini bir dal'a iter
      # İçerik, https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> adresinden veya github sayfası olarak kullanılabilir
      - name: Push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
